global_context:
  model_type: "qwen3_omni"

pipeline_modules:
  pipeline_params:
    type: "ParameterModule"
    outputs:
      - name: "videos"
        type: "VecOVTensor"
      - name: "images"
        type: "VecOVTensor"
      - name: "prompts"
        type: "VecString"
      - name: "audios"
        type: "VecOVTensor"
      - name: "use_audio_in_video"
        type: "VecInt"

  image_preprocessor:
    type: "ImagePreprocessModule"
    device: "CPU"
    description: "Image or Video preprocessing."
    inputs:
      - name: "images"
        type: "VecOVTensor"
        source: "pipeline_params.images"
    outputs:
      - name: "pixel_values"
        type: "VecOVTensor"
      - name: "grid_thw"
        type: "VecOVTensor"
      - name: "pos_embeds"
        type: "VecOVTensor"
      - name: "rotary_cos"
        type: "VecOVTensor"
      - name: "rotary_sin"
        type: "VecOVTensor"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen3-Omni-4B-Instruct-multilingual/"

  video_preprocessor:
    type: "VideoPreprocessModule"
    device: "CPU"
    description: "Video preprocessing."
    inputs:
      - name: "videos"
        type: "VecOVTensor"
        source: "pipeline_params.videos"
    outputs:
      - name: "pixel_values"
        type: "VecOVTensor"
      - name: "grid_thw"
        type: "VecOVTensor"
      - name: "pos_embeds"
        type: "VecOVTensor"
      - name: "rotary_cos"
        type: "VecOVTensor"
      - name: "rotary_sin"
        type: "VecOVTensor"
      - name: video_second_per_grid
        type: "VecInt"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen3-Omni-4B-Instruct-multilingual/"

  audio_preprocessor:
    type: "AudioPreprocessModule"
    device: "CPU"
    description: "Audio preprocessing."
    inputs:
      - name: "audios"
        type: "VecOVTensor"
        source: "pipeline_params.audios"
    outputs:
      - name: "input_features"
        type: "VecOVTensor"
      - name: "feature_attention_mask"
        type: "VecOVTensor"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen3-Omni-4B-Instruct-multilingual/"

  audio_encoder:
    type: "AudioEncoderModule"
    device: "GPU"
    description: "Audio encoder for Qwen 3-Omni."
    inputs:
      - name: "input_features"
        type: "VecOVTensor"
        source: "audio_preprocessor.input_features"
      - name: "feature_attention_mask"
        type: "VecOVTensor"
        source: "audio_preprocessor.feature_attention_mask"
    outputs:
      - name: "audio_features"
        type: "VecOVTensor"
      - name: "audio_feature_lengths"
        type: "OVTensor"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen3-Omni-4B-Instruct-multilingual/qwen3_omni_audio_encoder.xml"

  prompt_encoder:
    type: "TextEncoderModule"
    device: "GPU"
    inputs:
      - name: "prompts"
        type: "VecString"
        source: "pipeline_params.prompts"
      - name: "image_grid_thw"
        type: "VecOVTensor"
        source: "image_preprocessor.grid_thw"
      - name: "video_grid_thw"
        type: "VecOVTensor"
        source: "video_preprocessor.grid_thw"
      - name: "audio_features"
        type: "VecOVTensor"
        source: "audio_encoder.audio_features"
      - name: "video_second_per_grid"
        type: "VecInt"
        source: "video_preprocessor.video_second_per_grid"
      - name: "use_audio_in_video"
        type: "VecInt"
        source: "pipeline_params.use_audio_in_video"
    outputs:
      - name: "input_ids"
        type: "OVTensor"
      - name: "mask"
        type: "OVTensor"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen3-Omni-4B-Instruct-multilingual/"

  vision_encoder:
    type: "VisionEncoderModule"
    device: "GPU"
    inputs:
      - name: "preprocessed_image"
        type: "VecOVTensor"
        source: "image_preprocessor.pixel_values"
      - name: "image_grid_thw"
        type: "VecOVTensor"
        source: "image_preprocessor.grid_thw"
      - name: "image_pos_embeds"
        type: "VecOVTensor"
        source: "image_preprocessor.pos_embeds"
      - name: "image_rotary_cos"
        type: "VecOVTensor"
        source: "image_preprocessor.rotary_cos"
      - name: "image_rotary_sin"
        type: "VecOVTensor"
        source: "image_preprocessor.rotary_sin"
      - name: "preprocessed_video"
        type: "VecOVTensor"
        source: "video_preprocessor.pixel_values"
      - name: "video_grid_thw"
        type: "VecOVTensor"
        source: "video_preprocessor.grid_thw"
      - name: "video_pos_embeds"
        type: "VecOVTensor"
        source: "video_preprocessor.pos_embeds"
      - name: "video_rotary_cos"
        type: "VecOVTensor"
        source: "video_preprocessor.rotary_cos"
      - name: "video_rotary_sin"
        type: "VecOVTensor"
        source: "video_preprocessor.rotary_sin"
      - name: "input_ids"
        type: "OVTensor"
        source: "prompt_encoder.input_ids"
      - name: "attention_mask"
        type: "OVTensor"
        source: "prompt_encoder.mask"
      - name: "audio_features"
        type: "VecOVTensor"
        source: "audio_encoder.audio_features"
      - name: "audio_feature_lengths"
        type: "OVTensor"
        source: "audio_encoder.audio_feature_lengths"
    outputs:
      - name: "image_embedding"
        type: "OVTensor"
      - name: "visual_pos_mask"
        type: "OVTensor"
      - name: "position_ids"
        type: "OVTensor"
      - name: "rope_delta"
        type: "OVTensor"
      - name: "deepstack_embeds"
        type: "VecOVTensor"
      - name: "audio_embedding"
        type: "OVTensor"
      - name: "audio_pos_mask"
        type: "OVTensor"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen3-Omni-4B-Instruct-multilingual/qwen3_omni_vision_model.xml"
      vision_start_token_id: 248053

  llm:
    type: "LLMInferenceSDPAModule"
    device: "GPU"
    inputs:
      - name: "input_ids"
        type: "OVTensor"
        source: "prompt_encoder.input_ids"
      - name: "visual_embeds"
        type: "OVTensor"
        source: "vision_encoder.image_embedding"
      - name: "visual_pos_mask"
        type: "OVTensor"
        source: "vision_encoder.visual_pos_mask"
      - name: "grid_thw"
        type: "VecOVTensor"
        source: "video_preprocessor.grid_thw"
      - name: "position_ids"
        type: "OVTensor"
        source: "vision_encoder.position_ids"
      - name: "rope_delta"
        type: "OVTensor"
        source: "vision_encoder.rope_delta"
      - name: "deepstack_embeds"
        type: "VecOVTensor"
        source: "vision_encoder.deepstack_embeds"
      - name: "audio_embeds"
        type: "OVTensor"
        source: "vision_encoder.audio_embedding"
      - name: "audio_pos_mask"
        type: "OVTensor"
        source: "vision_encoder.audio_pos_mask"
    outputs:
      - name: "generated_text"
        type: "String"
    params:
      model_path: "./tests/module_genai/cpp/test_models/Qwen3-Omni-4B-Instruct-multilingual/qwen3_omni_text_model.xml"
      max_new_tokens: 512

  pipeline_result:
    type: "ResultModule"
    description: "Collects final results and formats the output structure."
    inputs:
      - name: "generated_text"
        type: "String"
        source: "llm.generated_text"